---
# main.yml tasks file for nutanix_role_get_info
- import_tasks: common/main.yml
  when: session_cookie is defined
- import_tasks: pc/main.yml
  when: >
    ( session_cookie is defined )
    ( prism_type == "pc" )
- import_tasks: pe/main.yml
  when: >
    ( session_cookie is defined )
    ( prism_type == "pe" )