---
# get_karbon_status.yml tasks file for nutanix_role_get_info
- name: Get KArbon Status
  uri:
    url: "{{ prism_api_v1 }}/genesis"
    body:
      value: "{\".oid\":\"ClusterManager\",\".method\":\"is_service_enabled\",\".kwargs\":{\"service_name\":\"KarbonUIService\"}}"
    method: POST
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ encoded_credentials }}"
  register: json_karbon_service_result
  ignore_errors: no

- name: Update fact karbon_enabled if KarbonUIService is enabled
  set_fact:
    karbon_enabled: true
  when:
    - '"true" in json_karbon_service_result.json'

- name: Debug | Print fact karbon_enabled
  debug:
    var: karbon_enabled
  when: global_debug